#!/usr/bin/env python3
"""翻译 apps/web 目录中的 UI 相关英文文本为中文。"""

import os
import re

# 核心 UI 翻译字典
UI_TRANSLATIONS = {
    # 通用
    "Loading": "加载中",
    "Loading...": "加载中...",
    "Failed": "失败",
    "Failed to load": "加载失败",
    "Failed to load agent": "加载代理失败",
    "Failed to load agents": "加载代理列表失败",
    "Failed to load entity": "加载实体失败",
    "Failed to load entities": "加载实体失败",
    "Failed to load epic": "加载史诗失败",
    "Failed to load epics": "加载史诗列表失败",
    "Failed to load project": "加载项目失败",
    "Failed to load projects": "加载项目列表失败",
    "Failed to load task": "加载任务失败",
    "Failed to load tasks": "加载任务列表失败",
    "Failed to load source": "加载数据源失败",
    "Failed to load sources": "加载数据源列表失败",
    "Failed to search": "搜索失败",
    "Search failed": "搜索失败",
    "No results found": "未找到结果",
    "No documentation found": "未找到文档",
    "Try different keywords or check if sources have been crawled": "请尝试其他关键词或检查数据源是否已爬取",
    "No data": "无数据",
    "No entities": "无实体",
    "No projects": "无项目",
    "No tasks": "无任务",
    "No sources": "无数据源",
    "No agents": "无智能代理",
    "No epics": "无史诗",
    "No documents": "无文档",
    "No clusters": "无集群",
    "Try again": "请重试",
    "Please try again later": "请稍后重试",
    "An internal error occurred": "服务器内部错误",
    "Please contact support": "请联系支持",
    "Contact support": "联系支持",
    "Support": "支持",
    "Help": "帮助",
    "Documentation": "文档",
    
    # 导航和菜单
    "Dashboard": "仪表板",
    "Agents": "智能代理",
    "Agent": "智能代理",
    "Entities": "知识实体",
    "Entity": "实体",
    "Epics": "史诗",
    "Epic": "史诗",
    "Projects": "项目",
    "Project": "项目",
    "Search": "搜索",
    "Graph": "图谱",
    "Sources": "数据源",
    "Source": "数据源",
    "Tasks": "任务",
    "Task": "任务",
    "Documents": "文档",
    "Document": "文档",
    "Settings": "设置",
    "Profile": "个人资料",
    "Preferences": "偏好设置",
    "Security": "安全",
    "Organizations": "组织",
    "Organization": "组织",
    "Teams": "团队",
    "Team": "团队",
    "Admin": "管理",
    "AI": "AI 设置",
    "System": "系统设置",
    "Backups": "备份设置",
    "Data": "数据设置",
    "Login": "登录",
    "Logout": "退出",
    "Sign In": "登录",
    "Sign Out": "退出",
    
    # 操作
    "Create": "创建",
    "Add": "添加",
    "Edit": "编辑",
    "Update": "更新",
    "Delete": "删除",
    "Remove": "移除",
    "View": "查看",
    "Details": "详情",
    "Overview": "概览",
    "Settings": "设置",
    "Configuration": "配置",
    "Properties": "属性",
    "Metadata": "元数据",
    "Relationships": "关系",
    "Related Entities": "相关实体",
    "Members": "成员",
    "Roles": "角色",
    "Permissions": "权限",
    "Invite": "邀请",
    "Accept": "接受",
    "Decline": "拒绝",
    "Pending": "待处理",
    "Active": "活跃",
    "Inactive": "不活跃",
    "Archived": "已归档",
    "Completed": "已完成",
    "In Progress": "进行中",
    "Blocked": "已阻塞",
    "Canceled": "已取消",
    "Success": "成功",
    "Warning": "警告",
    "Error": "错误",
    "Info": "提示",
    "Log": "日志",
    "Activity": "活动",
    "History": "历史",
    "Version": "版本",
    "Export": "导出",
    "Import": "导入",
    "Download": "下载",
    "Upload": "上传",
    "Share": "分享",
    "Copy": "复制",
    "Copied": "已复制",
    "Search": "搜索",
    "Filter": "筛选",
    "Sort": "排序",
    "Refresh": "刷新",
    "Clear": "清除",
    "Reset": "重置",
    "Save": "保存",
    "Cancel": "取消",
    "Confirm": "确认",
    "OK": "确定",
    "Yes": "是",
    "No": "否",
    "Close": "关闭",
    "Next": "下一步",
    "Previous": "上一步",
    "Finish": "完成",
    "Skip": "跳过",
    "Back": "返回",
    "Done": "完成",
    "Continue": "继续",
    "Start": "开始",
    "Stop": "停止",
    "Pause": "暂停",
    "Resume": "恢复",
    "Restart": "重新开始",
    "Retry": "重试",
    
    # 表单
    "Save": "保存",
    "Cancel": "取消",
    "Submit": "提交",
    "Reset": "重置",
    "Edit": "编辑",
    "Delete": "删除",
    "Confirm": "确认",
    "OK": "确定",
    "Yes": "是",
    "No": "否",
    "Close": "关闭",
    "Name": "名称",
    "Description": "描述",
    "Email": "邮箱",
    "Password": "密码",
    "Confirm Password": "确认密码",
    "Current Password": "当前密码",
    "New Password": "新密码",
    "Confirm New Password": "确认新密码",
    "Enter name": "输入名称",
    "Enter description": "输入描述",
    "Enter email": "输入邮箱",
    "Enter password": "输入密码",
    "Enter current password": "输入当前密码",
    "Enter new password": "输入新密码",
    "Enter confirm password": "输入确认密码",
    "Search...": "搜索...",
    "Enter search query": "输入搜索关键词",
    "Filter...": "筛选...",
    "Select...": "选择...",
    "Choose...": "选择...",
    "Upload...": "上传...",
    "Download...": "下载...",
    
    # 仪表板
    "Welcome": "欢迎",
    "Welcome to Sibyl": "欢迎使用 Sibyl",
    "Your development assistant": "您的开发助手",
    "Recent Activity": "最近活动",
    "Quick Actions": "快速操作",
    "Stats": "统计",
    "Metrics": "指标",
    "Velocity": "速度",
    "Entities": "实体",
    "Projects": "项目",
    "Tasks": "任务",
    "Sources": "数据源",
    "Agents": "智能代理",
    "Epics": "史诗",
    "Documents": "文档",
    "Clusters": "集群",
    "Relationships": "关系",
    "Nodes": "节点",
    "Edges": "边",
    "Paths": "路径",
    "Patterns": "模式",
    "Rules": "规则",
    "Triggers": "触发器",
    "Actions": "操作",
    "Workflows": "工作流",
    "Templates": "模板",
    "Examples": "示例",
    "Tutorials": "教程",
    "Guides": "指南",
    "Blog": "博客",
    "News": "新闻",
    "Events": "活动",
    "Videos": "视频",
    "Podcasts": "播客",
    "Webinars": "网络研讨会",
    "Workshops": "研讨会",
    "Talks": "演讲",
    "Slides": "幻灯片",
    "Demos": "演示",
    "Case Studies": "案例研究",
    "Testimonials": "客户评价",
    "Partners": "合作伙伴",
    "Integrations": "集成",
    "Plugins": "插件",
    "Extensions": "扩展",
    "Themes": "主题",
    "Components": "组件",
    "Libraries": "库",
    "Frameworks": "框架",
    "Tools": "工具",
    "Services": "服务",
    "APIs": "API",
    "Databases": "数据库",
    "Cloud": "云服务",
    "Hosting": "托管服务",
    "Storage": "存储服务",
    "CDN": "CDN 服务",
    "DNS": "DNS 服务",
    "SSL": "SSL 服务",
    "Domain": "域名服务",
    "Email": "邮件服务",
    "SMS": "短信服务",
    "Push": "推送服务",
    "Analytics": "分析服务",
    "Monitoring": "监控服务",
    "Logging": "日志服务",
    "Alerting": "告警服务",
    "Security": "安全服务",
    "Compliance": "合规服务",
    "Backup": "备份服务",
    "Recovery": "恢复服务",
    "Migration": "迁移服务",
    "Scaling": "扩展服务",
    "Optimization": "优化服务",
    "Performance": "性能服务",
    "Reliability": "可靠性服务",
    "Availability": "可用性服务",
    "Durability": "持久性服务",
    "Fault Tolerance": "容错服务",
    "Disaster Recovery": "灾难恢复服务",
    "High Availability": "高可用性服务",
    "Load Balancing": "负载均衡服务",
    "Auto Scaling": "自动扩展服务",
    "Caching": "缓存服务",
    "Queueing": "队列服务",
    "Messaging": "消息服务",
    "Streaming": "流服务",
    "Eventing": "事件服务",
    "Processing": "处理服务",
    "Computation": "计算服务",
    "Machine Learning": "机器学习服务",
    "AI": "AI 服务",
    "NLP": "自然语言处理服务",
    "Computer Vision": "计算机视觉服务",
    "Speech": "语音服务",
    "Translation": "翻译服务",
    "Summarization": "摘要服务",
    "Generation": "生成服务",
    "Classification": "分类服务",
    "Clustering": "聚类服务",
    "Regression": "回归服务",
    "Prediction": "预测服务",
    "Recommendation": "推荐服务",
    "Personalization": "个性化服务",
    "Simulation": "模拟服务",
    "Modeling": "建模服务",
    "Training": "训练服务",
    "Inference": "推理服务",
    "Governance": "治理服务",
    "Explainability": "可解释性服务",
    "Fairness": "公平性服务",
    "Privacy": "隐私服务",
    "Robustness": "鲁棒性服务",
    "Scalability": "扩展性服务",
    "Efficiency": "效率服务",
    "Cost": "成本服务",
    "Latency": "延迟服务",
    "Throughput": "吞吐量服务",
    "Accuracy": "准确性服务",
    "Precision": "精确性服务",
    "Recall": "召回率服务",
    "F1 Score": "F1 分数服务",
    "AUC": "AUC 服务",
    "Confusion Matrix": "混淆矩阵服务",
    "ROC Curve": "ROC 曲线服务",
    "Precision-Recall Curve": "精确率-召回率曲线服务",
    "Learning Curve": "学习曲线服务",
    "Training Curve": "训练曲线服务",
    "Validation Curve": "验证曲线服务",
    "Test Curve": "测试曲线服务",
    "Loss Curve": "损失曲线服务",
    "Accuracy Curve": "准确率曲线服务",
    "Precision Curve": "精确率曲线服务",
    "Recall Curve": "召回率曲线服务",
    "F1 Score Curve": "F1 分数曲线服务",
    "AUC Curve": "AUC 曲线服务",
    
    # 图表
    "Zoom in": "放大",
    "Zoom out": "缩小",
    "Fit to view": "适应视图",
    "Reset view": "重置视图",
    "Close panel": "关闭面板",
    "Nodes": "节点",
    "Edges": "边",
    "Clusters": "集群",
    "Relationships": "关系",
    "Network": "网络",
    "Graph": "图谱",
    "Chart": "图表",
    "Bar Chart": "柱状图",
    "Line Chart": "折线图",
    "Pie Chart": "饼图",
    "Area Chart": "面积图",
    "Scatter Plot": "散点图",
    "Heatmap": "热力图",
    "Histogram": "直方图",
    "Box Plot": "箱线图",
    "Violin Plot": "小提琴图",
    "Radar Chart": "雷达图",
    "Sankey Diagram": "桑基图",
    "Tree Map": "树图",
    "Sunburst Chart": "旭日图",
    "Word Cloud": "词云",
    "Network Graph": "网络图",
    "Force Directed Graph": "力导向图",
    "D3.js": "D3.js",
    "Chart.js": "Chart.js",
    "Plotly": "Plotly",
    "Vega": "Vega",
    "Vega-Lite": "Vega-Lite",
    "ECharts": "ECharts",
    "Highcharts": "Highcharts",
    "Google Charts": "Google Charts",
    "ApexCharts": "ApexCharts",
    "Recharts": "Recharts",
    "Victory": "Victory",
    "Nivo": "Nivo",
    "Dygraphs": "Dygraphs",
    "C3.js": "C3.js",
    "FusionCharts": "FusionCharts",
    "AnyChart": "AnyChart",
    "ZingChart": "ZingChart",
    "JSCharting": "JSCharting",
    "amCharts": "amCharts",
    "CanvasJS": "CanvasJS",
    "Chartist.js": "Chartist.js",
    "Flot": "Flot",
    "Morris.js": "Morris.js",
    "Rickshaw": "Rickshaw",
    "Sigma.js": "Sigma.js",
    "Vis.js": "Vis.js",
    "Three.js": "Three.js",
    "Babylon.js": "Babylon.js",
    "Cesium": "Cesium",
    "Leaflet": "Leaflet",
    "Mapbox GL JS": "Mapbox GL JS",
    "OpenLayers": "OpenLayers",
    "Google Maps JavaScript API": "Google Maps JavaScript API",
    "Bing Maps V8 Web Control": "Bing Maps V8 Web Control",
    "Here Maps JavaScript API": "Here Maps JavaScript API",
    "TomTom Maps SDK for Web": "TomTom Maps SDK for Web",
    "Esri ArcGIS API for JavaScript": "Esri ArcGIS API for JavaScript",
    "CARTO.js": "CARTO.js",
    "MapLibre GL JS": "MapLibre GL JS",
    "Deck.gl": "Deck.gl",
    "Kepler.gl": "Kepler.gl",
    "Uber H3": "Uber H3",
    "GeoJSON": "GeoJSON",
    "TopoJSON": "TopoJSON",
    "KML": "KML",
    "GPX": "GPX",
    "Shapefile": "Shapefile",
    "GeoTIFF": "GeoTIFF",
    "NetCDF": "NetCDF",
    "HDF5": "HDF5",
    "CSV": "CSV",
    "TSV": "TSV",
    "JSON": "JSON",
    "XML": "XML",
    "YAML": "YAML",
    "TOML": "TOML",
    "INI": "INI",
    "Properties": "Properties",
    "Config": "Config",
    "Settings": "Settings",
    "Environment": "Environment",
    "Variables": "Variables",
    "Constants": "Constants",
    "Parameters": "Parameters",
    "Arguments": "Arguments",
    "Options": "Options",
    "Flags": "Flags",
    "Switches": "Switches",
    "Parameters": "Parameters",
    "Arguments": "Arguments",
    "Options": "Options",
    "Flags": "Flags",
    "Switches": "Switches",
}

def is_ui_text(text):
    """判断是否为 UI 相关文本"""
    return text.isascii() and len(text) > 1 and '{' not in text and ' ' in text

def replace_in_file(filepath):
    """替换文件中的 UI 相关英文文本为中文。"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    changes = 0
    for english, chinese in UI_TRANSLATIONS.items():
        if f'"{english}"' in content and is_ui_text(english):
            content = content.replace(f'"{english}"', f'"{chinese}"')
            changes += 1
        if f"'{english}'" in content and is_ui_text(english):
            content = content.replace(f"'{english}'", f"'{chinese}'")
            changes += 1
    
    if changes > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"已翻译 {filepath}: {changes} 处")
        return changes
    return 0

def main():
    """主函数。"""
    total = 0
    file_count = 0
    
    for root, dirs, files in os.walk('apps/web'):
        rel_root = os.path.relpath(root, 'apps/web')
        if any(skip in rel_root.lower() for skip in ['test', 'node_modules', '.git', '.storybook', '.next']):
            continue
        for f in files:
            if f.endswith(('.ts', '.tsx', '.js', '.jsx')):
                filepath = os.path.join(root, f)
                changes = replace_in_file(filepath)
                if changes > 0:
                    total += changes
                    file_count += 1
    
    print(f"\n翻译完成！共翻译 {total} 处 UI 文本到 {file_count} 个文件")

if __name__ == '__main__':
    main()
