"""drop_graph_name_from_organizations

Revision ID: ae2c1a74e94a
Revises: b0614e6f7ae3
Create Date: 2025-12-23 13:51:14.075907

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae2c1a74e94a"
down_revision: str | Sequence[str] | None = "b0614e6f7ae3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "graph_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("graph_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
