# https://moonrepo.dev/docs/config/workspace
$schema: "./cache/schemas/workspace.json"

vcs:
  manager: git
  defaultBranch: main

# Only allow node to auto-install deps; Python handled by root:sync task
pipeline:
  installDependencies:
    - node

projects:
  root: "."
  api: "apps/api"
  cli: "apps/cli"
  e2e: "apps/e2e"
  web: "apps/web"
  docs: "docs"
  # Shared packages
  core: "packages/python/sibyl-core"
  # Tools
  hooks: "hooks"
  skills: "skills"
  infra: "infra"
